{{- range $lbName, $lb := .Values.loadBalancers }}
{{- if $lb.enabled }}
{{- $loadBalancerLabels := (include "loadBalancerLabels" (dict "root" $ "lbName" $lbName)) }}
{{- $commonLBLabels := (include "commonLBLabels" (dict "root" $ "lbName" $lbName)) }}
{{- $loadBalancerServiceAccountName := (include "loadBalancerServiceAccountName" (dict "root" $ "lbName" $lbName)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $loadBalancerServiceAccountName }}
  labels: {{- $commonLBLabels | nindent 4 }}
{{ $loadBalancerLabels | indent 4 -}}
  {{- with $lb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}